[CI] : Update linux workflow to instantiate python versions correctly.

diff --git a/.github/workflows/buildReleaseAndPublish.yml b/.github/workflows/buildReleaseAndPublish.yml
--- a/.github/workflows/buildReleaseAndPublish.yml
+++ b/.github/workflows/buildReleaseAndPublish.yml
@@ -25,8 +25,15 @@ jobs:
     strategy:
       matrix:
         package: [torch-mlir]
-        py_version: [cp310-cp310, cp311-cp311, cp312-cp312]
         arch: [x86_64, AArch64]
+        py_version: ['3.10', '3.11', '3.12']
+        include:
+          - py_version: '3.10'
+            py_tag: 'cp310-cp310'
+          - py_version: '3.11'
+            py_tag: 'cp311-cp311'
+          - py_version: '3.12'
+            py_tag: 'cp312-cp312'
 
     runs-on: ${{ matrix.arch == 'AArch64' && 'ubuntu-24.04-arm' || 'ubuntu-24.04' }}
 
@@ -40,6 +47,20 @@ jobs:
 
       - name: Setup workspace
         uses: ./.github/actions/setup-build
+        with:
+          python-version: ${{ matrix.py_version }}
+
+      - name: Verify python version
+        run: |          
+          # extract python major.minor version, for example, extract 3.10 from version 3.10.12
+          actual_version=$(python --version | cut -d' ' -f2 | cut -d'.' -f1,2)
+          expected_version="${{ matrix.py_version }}"
+          
+          if [ "$actual_version" != "$expected_version" ]; then
+            echo "ERROR: Python version mismatch! Expected $expected_version but got $actual_version"
+            exit 1
+          fi
+          echo "Python version verified: Expected $expected_version and got $actual_version"
 
       - name: Build Python wheels and smoke test
         run: |
@@ -47,7 +68,7 @@ jobs:
           tm_package_version="$(printf '%(%Y%m%d)T.${{ github.run_number }}')"
           echo "tm_package_version=${tm_package_version}" >> $GITHUB_ENV
           printf "TORCH_MLIR_PYTHON_PACKAGE_VERSION=%s\n" ${tm_package_version} > ./torch_mlir_package_version
-          TM_PYTHON_VERSIONS=${{ matrix.py_version }} TM_PACKAGES=${{ matrix.package }} ./build_tools/python_deploy/build_linux_packages.sh
+          TM_PYTHON_VERSIONS=${{ matrix.py_tag }} TM_PACKAGES=${{ matrix.package }} ./build_tools/python_deploy/build_linux_packages.sh
 
       - name: Make assets available in dist
         run: |
@@ -58,7 +79,7 @@ jobs:
         uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
         with:
           if-no-files-found: error
-          name: snapshot-${{ matrix.package }}-${{ matrix.arch }}-${{ matrix.py_version }}-${{ env.tm_package_version }}
+          name: snapshot-${{ matrix.package }}-${{ matrix.arch }}-${{ matrix.py_tag }}-${{ env.tm_package_version }}
           path: dist
 
       - name: Release python wheels
