[Task] : Enable windows build for py versions other than 3.11

diff --git a/.github/workflows/buildReleaseAndPublishWindows.yml b/.github/workflows/buildReleaseAndPublishWindows.yml
--- a/.github/workflows/buildReleaseAndPublishWindows.yml
+++ b/.github/workflows/buildReleaseAndPublishWindows.yml
@@ -29,9 +29,14 @@ jobs:
     strategy:
       matrix:
         package: [torch-mlir]
-        # TODO(#10): `py_version` has no effect and wheels only get build for 3.11.
-        # py_version: [cp310-cp310, cp311-cp311, cp312-cp312]
-        py_version: [cp311-cp311]
+        py_version: ['3.10', '3.11', '3.12']
+        include:
+          - py_version: '3.10'
+            py_tag: 'cp310-cp310'
+          - py_version: '3.11'
+            py_tag: 'cp311-cp311'
+          - py_version: '3.12'
+            py_tag: 'cp312-cp312'
 
     steps:
       - name: Checkout torch-mlir
@@ -41,8 +46,22 @@ jobs:
           ref: refs/heads/main
           submodules: 'true'
 
-      - name: Setup workspace
+      - name: Setup workspace and python
         uses: ./.github/actions/setup-build
+        with:
+          python-version: ${{ matrix.py_version }}
+
+      - name: Verify python version
+        run: |          
+          # extract python major.minor version, for example, extract 3.10 from version 3.10.12
+          actual_version=$(python --version | cut -d' ' -f2 | cut -d'.' -f1,2)
+          expected_version="${{ matrix.py_version }}"
+          
+          if [ "$actual_version" != "$expected_version" ]; then
+            echo "ERROR: Python version mismatch! Expected $expected_version but got $actual_version"
+            exit 1
+          fi
+          echo "Python version verified: Expected $expected_version and got $actual_version"
 
       - name: "Configuring MSVC"
         uses: ilammy/msvc-dev-cmd@0b201ec74fa43914dc39ae48a89fd1d8cb592756 # v1.13.0
@@ -65,7 +84,7 @@ jobs:
         uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
         with:
           if-no-files-found: error
-          name: snapshot-${{ matrix.package }}-${{ matrix.py_version }}-${{ env.tm_package_version }}
+          name: snapshot-${{ matrix.package }}-${{ matrix.py_tag }}-${{ env.tm_package_version }}
           path: dist
 
       - name: Release python wheels
